
default: &default
  adapter: postgresql
  encoding: utf8
  
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: my_first_app_development

test:
  <<: *default
  database: my_first_app_test


production:
  <<: *default
  database: my_first_app_production
  username: my_first_app
  password: <%= ENV['MY_FIRST_APP_DATABASE_PASSWORD'] %>
